#! /bin/bash
#
# testall:  run all package tests
#
set -e
prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
PACKAGE_DIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
MVN=${MAVEN_CMD:-$PACKAGE_DIR/mvnw}

$PACKAGE_DIR/scripts/setversion.sh
"$MVN" test
